---

- name: YUM | Install epel-release and yum-utils
  yum:
    name:
      - epel-release
      - yum-utils
    state: present

- name: COPY | Replace epel-release repository definition
  copy:
    register: _epel
    dest: /etc/yum.repos.d/epel.repo
    content: |
      [epel]
      name=Extra Packages for Enterprise Linux $releasever - $basearch
      baseurl=http://fedora-epel.mirror.iweb.ca/$releasever/$basearch
      failovermethod=priority
      enabled=1
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

- name: COMMAND | yum clean metadata when epel.repo change (just to be safe)
  command: yum clean metadata
  args:
    warn: no
  when: _epel.changed

# Since we enforce repo_gpgcheck=1 globally in ul_stig and that EPEL .repo files don't
# ship with this flag disabled, we must force it.
#
# At first, we use a brute force and non deterministic method with yum-config-manager.
#
# TODO: We could improve this step by carefully defining all required fields and by
#       using yum_repository module. Also, specifying an HTTP mirror will make efficient
#       use of proxy caching (eg: Squid).
#
# Bogus under centos 7
# - name: COMMAND | Remove repo_gpgcheck from EPEL repositories
#   command: "yum-config-manager --save --setopt={{ item }}.repo_gpgcheck=0"
#   changed_when: false
#   with_items: "{{ _common_epel_repos }}"

- name: YUM | Install common packages
  yum:
    name: "{{ _common_packages }}"
    state: present
