---

# This block is executed when _common_system_upgrade_tag is non-empty

- block:

    # Check current state

    - name: STAT | Check /etc/coda19/system-upgrade
      stat:
        path: /etc/coda19/system-upgrade
      register: _system_upgrade_stat

    - name: SLURP | Fetch /etc/coda19/system-upgrade content
      slurp:
        src: /etc/coda19/system-upgrade
      register: _system_upgrade_tag
      when: _system_upgrade_stat.stat.exists

    # Trigger update, register and reboot when needed

    - block:

        - name: YUM | Update all packages to latest
          yum:
            name: "*"
            state: latest
            update_cache: yes
          register: _yum

        - name: COPY | Mark this update as done
          copy:
            dest: /etc/coda19/system-upgrade
            content: "{{ _common_system_upgrade_tag }}"

        - name: REBOOT | Reboot system if yum changed something
          reboot:
          when: _yum.changed

      when: not _system_upgrade_stat.stat.exists or  _system_upgrade_tag.content|b64decode != _common_system_upgrade_tag

  when:
    - _common_system_upgrade_tag | length > 0
