---

#------------------------------------------------------------------------------
# CENTOS 7
#------------------------------------------------------------------------------
#
# Reference: https://podman.io/getting-started/installation
#

- block:

    #### curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo \
    ####      https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo

    - name: COPY | Create upstream respository file (/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo)
      copy:
        dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
        content: |
          [devel_kubic_libcontainers_stable]
          name=Stable Releases of Upstream github.com/containers packages (CentOS_7)
          type=rpm-md
          #baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
          baseurl=https://ftp.gwdg.de/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
          gpgcheck=1
          #gpgkey=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/repodata/repomd.xml.key
          gpgkey=https://ftp.gwdg.de/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/repodata/repomd.xml.key
          enabled=1

  when:
    - ul_podman_install_upstream|bool
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

#------------------------------------------------------------------------------
# CENTOS 8
#------------------------------------------------------------------------------
#
# Reference: https://podman.io/getting-started/installation
#

- block:

    #### dnf -y module disable container-tools
    #
    # dnf module not supporting well modules management
    # See: https://github.com/ansible/ansible/issues/64852
    # We simply put a file, that is identical than generated by:
    #   dnf -qy module disable container-tools
    #
    - name: COPY | Disable container-tools module stream (/etc/dnf/modules.d/container-tools.module)
      copy:
        dest: /etc/dnf/modules.d/container-tools.module
        content: |
          [container-tools]
          name=container-tools
          stream=
          profiles=
          state=disabled

    ##### dnf -y install 'dnf-command(copr)'

    - name: DNF | Install dnf-plugins-core / dnf-command(copr)
      dnf:
        name: dnf-plugins-core
        state: present

    #### dnf -y copr enable rhcontainerbot/container-selinux

    # OPTION 1 : Invoke command and detect

    - name: COMMAND | dnf -y copr enable rhcontainerbot/container-selinux
      command: dnf -y copr enable rhcontainerbot/container-selinux
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:rhcontainerbot:container-selinux.repo

    # OPTION 2 : Copy repository content

    # - name: COPY | Create COPR rhcontainerbot/container-selinux repository
    #   copy:
    #     dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:rhcontainerbot:container-selinux.repo
    #     content: |
    #       [copr:copr.fedorainfracloud.org:rhcontainerbot:container-selinux]
    #       name=Copr repo for container-selinux owned by rhcontainerbot
    #       baseurl=https://download.copr.fedorainfracloud.org/results/rhcontainerbot/container-selinux/epel-8-$basearch/
    #       type=rpm-md
    #       skip_if_unavailable=True
    #       gpgcheck=1
    #       gpgkey=https://download.copr.fedorainfracloud.org/results/rhcontainerbot/container-selinux/pubkey.gpg
    #       repo_gpgcheck=0
    #       enabled=1
    #       enabled_metadata=1

    #### curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo \
    ####      https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo

    - name: COPY | Create upstream respository file (/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo)
      copy:
        dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
        content: |
          [devel_kubic_libcontainers_stable]
          name=Stable Releases of Upstream github.com/containers packages (CentOS_8)
          type=rpm-md
          baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/
          gpgcheck=1
          gpgkey=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/repodata/repomd.xml.key
          enabled=1

  when:
    - ul_podman_install_upstream|bool
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '8'
