---

# CENTOS 7
#sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
#sudo yum -y install podman

# CENTOS 8
#sudo dnf -y module disable container-tools
#sudo dnf -y install 'dnf-command(copr)'
#sudo dnf -y copr enable rhcontainerbot/container-selinux
#sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
#sudo dnf -y install podman
