---


- name: YUM | Install all the required dependencies
  yum:
    name:
      - ca-certificates
      - python-psycopg2
      - python-pycurl
      - glibc-common
      - epel-release
      - libselinux-python
    state: present

- name: YUM | Install PostgreSQL packages
  yum:
    name:
      - "postgresql{{ ul_postgresql_version_terse }}"
      - "postgresql{{ ul_postgresql_version_terse }}-server"
      - "postgresql{{ ul_postgresql_version_terse }}-contrib"
      - "postgresql{{ ul_postgresql_version_terse }}-llvmjit"
    state: present
  environment: "{{ ul_postgresql_env }}"
