---

# TODO: ansible_distribution --> ansible_os_family
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution | lower }}.yml"
    - "../vars/empty.yml"
  tags:
    - always

- name: "IMPORT_TASKS | repository.yml"
  import_tasks: repository.yml
  tags:
    - ul_postgresql
    - ul_postgresql_repository

- name: "IMPORT_TASKS | install.yml"
  import_tasks: install.yml
  tags:
    - ul_postgresql
    - ul_postgresql_install

- name: IMPORT_TASKS | reset.yml
  import_tasks: reset.yml
  when:
    - ul_postgresql_reset is defined
    - ul_postgresql_reset | bool
  tags:
    - ul_postgresql
    - ul_postgresql_reset

- name: IMPORT_TASKS | prepare.yml
  import_tasks: prepare.yml
  tags:
    - ul_postgresql
    - ul_postgresql_prepare

- name: "IMPORT_TASKS | configure.yml"
  import_tasks: configure.yml
  tags:
    - ul_postgresql
    - ul_postgresql_configure

- name: "IMPORT_TASKS | extensions.yml"
  import_tasks: extensions.yml
  tags:
    - ul_postgresql
    - ul_postgresql_extensions

- name: "IMPORT_TASKS | manage.yml"
  import_tasks: manage.yml
  tags:
    - ul_postgresql
    - ul_postgresql_manage
