---
# OneOffs are globally disabled (enabled per site, see group_vars)

- debug:
    msg: "coda19_host_role => {{ coda19_host_role }} / _oneoffs_migration_fhir4 => {{ _oneoffs_migration_fhir4 }}"

- name: "IMPORT_TASKS | oneoffs/01-upgrade-fihr-v3-to-v4 (for orange VMs)"
  import_tasks: 01-upgrade-fihr-v3-to-v4.yml
  tags:
      - ul_oneoffs
      - ul_oneoffs_aidbox_fihr_migration
  when: _oneoffs_migration_fhir4 and  coda19_host_role == 'orange'


  # brlav, 2021-10-08
  #   ul_nginx not used yet and troublesome for s119, juste remove for now
  #   by removing /etc/yum.repos.d/nginx.conf

  - name: FILE | Ensure that /etc/yum.repos.d/nginx.conf absent
    file:
      path: /etc/yum.repos.d/nginx.conf
      state: absent
