---

########## TRY TO FIX ORTHANC USER

- name: SET_FACT | _cookie_value + _cookie_file
  set_fact:
    _cookie_value: "20220726-02"
    _cookie_file: /etc/coda19/oneoff-fix-orthanc-user

- when:
    - coda19_site_id|int == 110
    - coda19_host_role == 'orange'
  block:

    - name: "SLURP | Check for cookie file - {{ _cookie_file }}"
      slurp:
        src: "{{ _cookie_file }}"
      ignore_errors: yes
      register: _slurp

    - when: _slurp.failed or _slurp['content'] | b64decode | string != _cookie_value | string
      block:

        - name: SYSTEMD | Stop orthanc service
          systemd:
            name: orthanc
            state: stopped

        - name: SHELL | Kill all remaining orthanc user processes
          shell: |
            pkill -U orthanc --signal SIGKILL
            pkill -u orthanc --signal SIGKILL

        - name: USER | Remove orthanc user
          user:
            name: orthanc
            state: absent
            remove: yes
            force: yes

        - name: COPY | Mark as done
          copy:
            dest: "{{ _cookie_file }}"
            content: "{{ _cookie_value }}"
