---

- name: restart aidboxdb
  systemd:
    name: aidboxdb
    state: restarted
    enabled: yes
    daemon_reload: yes
  # Don't start + restart service with handlers, usualy on first run
  when: not _systemd_aidboxdb.changed

- name: restart aidbox
  systemd:
    name: aidbox
    state: restarted
    enabled: yes
    daemon_reload: yes
  # Don't start + restart service with handlers, usualy on first run
  when: not _systemd_aidbox.changed
