---

# Control Plane Address

ul_coda19_green_hub_api_url: 	https://api.hub.coda19.com

ul_coda19_green_firewalld_zones:
  - zone: public
    state: enabled

ul_coda19_docker_image_registry: docker.io

################################################################################
#### CODA19-SITE-API
################################################################################

# Listening port (TCP)
coda19_site_api_port: 5148

# Environnement variables
coda19_site_api_keycloak_url_and_realm: https://auth.hub.coda19.com/auth/realms/coda19-pr/
coda19_site_api_keycloak_client_id: coda19-site
coda19_site_api_stats_api_endpoint:

# Image and tag to use
coda19_site_api_image_name: coda19/coda19-site-api
coda19_site_api_image_tag: latest

################################################################################
#### CODA19-STATS-API
################################################################################

# Listening port (TCP)
coda19_stats_api_port: 5427

# Environnement variables
coda19_stats_api_fake_aidbox: true
coda19_stats_api_aidbox_url:
coda19_stats_api_aidbox_token:

  # Image and tag to use
coda19_stats_api_image_name: coda19/coda19-stats-api
coda19_stats_api_image_tag: latest

################################################################################
#### General and common stuff
################################################################################

# Systemd stuff
ul_coda19_green_systemd_temp_dir: "{{ '/tmp' if ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7 else '%T' }}"
ul_coda19_green_systemd_timeout_start_sec: 120
ul_coda19_green_systemd_restart_sec: 15

# Podman stuff
ul_coda19_green_container_stop_timeout: 5
ul_coda19_green_container_cidfile: "{{ ul_coda19_green_systemd_temp_dir }}/%n-cid"
ul_coda19_green_container_pidfile: "{{ ul_coda19_green_systemd_temp_dir }}/%n-pid"
