---

# Sets up a local user 'coda' and its subuid/subgid for a rootless container

- name: GROUP | Add the group 'coda'
  group:
    name: coda
    system: yes

- name: USER | Add the user 'coda'
  user:
    name: coda
    comment: CODA Purple Service account
    group: coda
    system: no

# Where the config stuff goes

- name: FILE | Ensure /etc/coda is present
  file:
    dest: /etc/coda
    owner: coda
    group: coda
    mode: 0750
    state: directory

# Generate the file that contains the variables for the REST service container

- name: TEMPLATE | Generate /etc/coda/coda_purple_vars
  template:
    src: etc/coda/coda_purple_vars.j2
    dest: /etc/coda/coda_purple_vars
    owner: coda
    group: coda
    mode: 0640

# Generates the systemd workunit

- name: TEMPLATE | Generate systemd service unit
  template:
    src: etc/systemd/system/coda_purple.service.j2
    dest: /etc/systemd/system/coda_purple.service
    owner: root
    group: root
    mode: 0664

# 'podman system migrate' is required else, an error will be thrown :
# "there might not be enough IDs available in the namespace (requested 0:42 for /etc/gshadow): lchown /etc/gshadow: invalid argument"
- name: COMMAND | podman system migrate
  command: /bin/podman system migrate
  become: yes
  become_user: coda

#TODO: Prefetch podman image
