---

# ULAVAL SPECIFIC STUFF, SHOULD NOT BE HERE
- name: SYSTEMD | Ensutre cockpit is stopped and disabled
  systemd:
    name: cockpit.socket
    state: stopped
    enabled: no

- name: SYSTEMD | Ensure prometheus service is started and enabled
  systemd:
    name: prometheus
    state: started
    enabled: yes
