---
# Creates a database for FHIR Base
- name: POSTGRESQL_USER | Creates database user
  postgresql_user:
    name: "{{ ul_aidbox_db_owner }}"
    # See vault files (password differs between sites), enforce md5 security
    # The REST API do some operations (GRANT, etc) that requires a superuser :(
    password: "{{ 'md5'+((ul_aidbox_db_password+ul_aidbox_db_owner) | hash('MD5')) }}"
    role_attr_flags: LOGIN,SUPERUSER
  become: true
  become_user: postgres

- name: POSTGRESQL_DB | Creates database with "{{ ul_aidbox_db_owner }}" as owner
  postgresql_db:
    name: "{{ ul_aidbox_db_name }}"
    owner: "{{ ul_aidbox_db_owner }}"
  become: true
  become_user: postgres

# Pre-creates a number of extensions used by the REST service and fhirbase, this avoids to have a SUPERUSER account
# pg_trgm & pg_stat_statements require postgresql-contrib to be installed (see role ul_postgresql)
- name: POSTGRESQL_EXT | Creates required extensions
  postgresql_ext:
    db: "{{ ul_aidbox_db_name }}"
    name: "{{ item }}"
  become: true
  become_user: postgres
  loop:
    - pgcrypto
    - pg_stat_statements
    - fuzzystrmatch
    - pg_trgm
    - unaccent
