---

- name: AIDBOXDB | GROUP | Add the group 'aidboxdb'
  group:
    name: aidboxdb
    system: no

- name: AIDBOXDB | USER | Add the user 'aidboxdb'
  user:
    name: aidboxdb
    comment: AidBox DB Service account
    group: aidboxdb
    home: /var/lib/aidboxdb
    system: no
  register: _user

- name: AIDBOXDB | TEMPLATE | Generate /etc/default/aidboxdb
  template:
    src: etc/default/aidboxdb.j2
    dest: /etc/default/aidboxdb
    owner: aidboxdb
    group: aidboxdb
    mode: 0640
  notify:
    - restart aidboxdb

- name: AIDBOXDB | TEMPLATE | Copy systemd service unit
  template:
    src: etc/systemd/system/aidboxdb.service.j2
    dest: /etc/systemd/system/aidboxdb.service
    owner: root
    group: root
    mode: 0664
  notify:
    - restart aidboxdb

# Create data directory
- name: AIDBOXDB | FILE | Ensure /data/aidboxdb is present
  file:
    dest: /data/aidboxdb
    owner: aidboxdb
    group: aidboxdb
    mode: 0700
    state: directory

# Check if local and remote image signature matches and, if not the case, pull it
- name: INCLUDE_TASKS | check-pull-image.yml
  include_tasks: check-pull-image.yml
  vars:
    container_name: aidboxdb
    image_registry: "{{ ul_aidbox_db_image_registry }}"
    image_name: "{{ ul_aidbox_db_image_name }}"
    image_tag: "{{ ul_aidbox_db_image_tag }}"

- name: AIDBOXDB | SYSTEMD | Ensure aidboxdb.service is started and enabled
  systemd:
    name: aidboxdb
    state: started
    enabled: yes
    daemon_reload: yes
  # We register this task status.
  # Don't start + restart service with handlers, usualy on first run.
  register: _systemd_aidboxdb

- meta: flush_handlers
