---

- name: AIDBOX | GROUP | Add the group 'aidbox'
  group:
    name: aidbox
    system: no

- name: AIDBOX | USER | Add the user 'aidbox'
  user:
    name: aidbox
    comment: AidBox Service account
    group: aidbox
    home: /var/lib/aidbox
    system: no
  register: _user

- name: AIDBOX | TEMPLATE | Generate /etc/default/aidbox
  template:
    src: etc/default/aidbox.j2
    dest: /etc/default/aidbox
    owner: aidbox
    group: aidbox
    mode: 0640
  notify:
    - restart aidbox

- name: AIDBOX | TEMPLATE | Copy systemd service unit
  template:
    src: etc/systemd/system/aidbox.service.j2
    dest: /etc/systemd/system/aidbox.service
    owner: root
    group: root
    mode: 0664
  notify:
    - restart aidbox

# Create data directory
- name: AIDBOX | FILE | Ensure /data/aidbox is present
  file:
    dest: /data/aidbox
    owner: aidbox
    group: aidbox
    mode: 0750
    state: directory

### Invoke the puller

- name: "INCLUDE_TASKS | roles/ul_podman/tasks/puller.yml"
  include_tasks: "{{ inventory_dir }}/roles/ul_podman/tasks/puller.yml"
  vars:
    _image_repo: "{{ ul_aidbox_image_registry}}"
    _image_name: "{{ ul_aidbox_image_name }}"
    _image_tag: "{{ ul_aidbox_image_tag }}"
    _image_user: aidbox
    _image_change_handler: restart aidbox
    _image_prune_enabled: true
    _remote_check_hours: "{{ ul_aidbox_image_remote_check_hours }}"
    _remote_check_runs: "{{ ul_aidbox_image_remote_check_runs }}"

### Start and enable service

- name: AIDBOX | SYSTEMD | Ensure aidbox.service is started and enabled
  systemd:
    name: aidbox
    state: started
    enabled: yes
    daemon_reload: yes
  # We register this task status.
  # Don't start + restart service with handlers, usualy on first run.
  register: _systemd_aidbox

- meta: flush_handlers
