---

# - name: "IMPORT_TASKS | oneoffs/01"
#   import_tasks: oneoffs/01-upgrade-fihr-v3-to-v4.yml
#   tags:
#     - ul_aidbox
#     - ul_aidbox_migration_firh

- name: "IMPORT_TASKS | firewall.yml"
  import_tasks: firewall.yml
  tags:
    - ul_aidbox
    - ul_aidbox_firewall

- name: "IMPORT_TASKS | install-aidboxdb.yml"
  import_tasks: install-aidboxdb.yml
  tags:
    - ul_aidbox
    - ul_aidbox_install
    - ul_aidbox_install_aidboxdb

- name: "IMPORT_TASKS | install-aidbox.yml"
  import_tasks: install-aidbox.yml
  tags:
    - ul_aidbox
    - ul_aidbox_install
    - ul_aidbox_install_aidbox
