---
- name: "IMPORT_TASKS | firewall.yml"
  import_tasks: firewall.yml
  tags:
    - ul_aidbox
    - ul_aidbox_firewall

- name: "IMPORT_TASKS | install.yml"
  import_tasks: install.yml
  tags:
    - ul_aidbox
    - ul_aidbox_install
