---
- name: "IMPORT_TASKS | database.yml"
  import_tasks: database.yml
  tags:
    - ul_aidbox
    - ul_aidbox_database

- name: "IMPORT_TASKS | aidboxone.yml"
  import_tasks: aidboxone.yml
  tags:
    - ul_aidbox
    - ul_aidbox_one
