---

#### MANAGE PROXY

- name: FILE | Create /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: TEMPLATE | Generate file /etc/systemd/system/docker.service.d/http-proxy.conf
  template:
    src: etc/systemd/system/http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: ul_docker_proxy|length > 0
  notify:
    - restart docker

- name: FILE | Remove file /etc/systemd/system/docker.service.d/http-proxy.conf
  file:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: absent
  when: ul_docker_proxy|length == 0
  notify:
    - restart docker
