---
###### SERVER - COMMON

- name: "FAIL | Check if minimal configuration is provided"
  fail:
    msg: "You must define ul_minio_server_access_key and ul_minio_server_secret_key variables."
  when:
    not ul_minio_server_access_key or ul_minio_server_access_key is not defined or
    not ul_minio_server_access_key or ul_minio_server_access_key is not defined

- name: "USER | Create MINIO user"
  user:
    name: minio
    system: yes
    shell: /sbin/nologin
    home: "{{ ul_minio_home_dir }}"

###### SERVER

# C7-3145
# Minio changed his backing store: https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html
# Error we got:
#   Feb 01 15:01:03 recherche-coda19-orange minio[12564]: ERROR Unable to use the drive /data/minio: Drive /data/minio: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified
# Instead of migrating, we manually fetch the latest working version from this rpm:
#   https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20221024183507.0.0.x86_64.rpm
#
# FIXME: use rpm installation instead of binary distribution trough this git repo, this will need refactor + data migration

# - name: "GET_URL | Download MINIO server"
#   get_url:
#     url: https://dl.min.io/server/minio/release/linux-amd64/minio
#     dest: /usr/local/bin/minio
#     mode: 0755
#     timeout: 30
#   notify: restart minio

- name: COPY | /usr/local/bin/minio
  copy:
    src: files/minio
    dest: /usr/local/bin/mino
    owner: root
    group: root
    mode: 0755
  notify: restart minio

- name: "TEMPLATE | Generate config - /etc/default/minio"
  template:
    src: etc/default/minio.j2
    dest: /etc/default/minio
    owner: minio
    group: minio
    mode: 0600
  notify: restart minio

- name: "TEMPLATE | Generate systemd service unit - /etc/systemd/system/minio.service"
  template:
    src: etc/systemd/system/minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: "SYSTEMD | Ensure that service is started and enabled"
  systemd:
    name: minio
    daemon_reload: yes
    state: started
    enabled: yes

# TODO: FIX BUG

#- name: "COMMAND | Configure MC «local» alias with configured keys"
#  command: "/usr/local/bin/mc alias set local http://localhost:9000 {{ ul_minio_server_access_key }} {{ ul_minio_server_secret_key }}"
#  no_log: yes
#  register: _return
#   changed_when: false
