---
###### SERVER - COMMON

- name: "FAIL | Check if minimal configuration is provided"
  fail:
    msg: "You must define ul_minio_server_access_key and ul_minio_server_secret_key variables."
  when:
    not ul_minio_server_access_key or ul_minio_server_access_key is not defined or
    not ul_minio_server_access_key or ul_minio_server_access_key is not defined

# TODO: what happens if directory exist and previously provisioned by an lvm mountpoint (ul_lvm) ?
- name: "USER | Create MINIO user"
  user:
    name: minio
    system: yes
    shell: /sbin/nologin
    home: /var/lib/minio

###### SERVER

# TODO: don't overwrite binary if already existent, we must update using «mc admin update»

- name: "GET_URL | Download MINIO server"
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: 0755

- name: "TEMPLATE | Generate config - /etc/default/minio"
  template:
    src: etc/default/minio.j2
    dest: /etc/default/minio
    owner: minio
    group: minio
    mode: 0600
  notify: restart minio

- name: "TEMPLATE | Generate systemd service unit - /etc/systemd/system/minio.service"
  template:
    src: etc/systemd/system/minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: "SYSTEMD | Ensure that service is started and enabled"
  systemd:
    name: minio
    daemon_reload: yes
    state: started
    enabled: yes

# TODO: FIX BUG

#- name: "COMMAND | Configure MC «local» alias with configured keys"
#  command: "/usr/local/bin/mc alias set local http://localhost:9000 {{ ul_minio_server_access_key }} {{ ul_minio_server_secret_key }}"
#  no_log: yes
#  register: _return
#   changed_when: false
