---
# Sets up a local user 'coda' and its subuid/subgid for a rootless container
- name: GROUP | Add the group 'coda'
  group:
    name: coda
    system: yes

- name: USER | Add the user 'coda'
  user:
    name: coda
    comment: CODA Green Service account
    group: coda
    system: no

# Where the config stuff goes

- name: FILE | Ensure /etc/coda is present
  file:
    dest: /etc/coda
    owner: coda
    group: coda
    mode: 0750
    state: directory

# Generate the file that contains the variables for the REST service container

- name: TEMPLATE | Generate /etc/coda/coda_green_vars
  template:
    src: etc/coda/coda_green_vars.j2
    dest: /etc/coda/coda_green_vars
    owner: coda
    group: coda
    mode: 0640

# Generates the systemd workunit

- name: TEMPLATE | Generate systemd service unit
  template:
    src: etc/systemd/system/coda_green.service.j2
    dest: /etc/systemd/system/coda_green.service
    owner: root
    group: root
    mode: 0664

# Generates the wrapper script for Coda Green
- name: TEMPLATE | Copy the wrapper script for Coda green
  template:
    src: usr/local/sbin/coda_green_podman_wrapper.sh.j2
    dest: /usr/local/sbin/coda_green_podman_wrapper.sh
    owner: root
    group: root
    mode: 0770

# Install the cron job that will check/pull the podman image and start the service upon it next run
# The script has been installed by the ul_podman role
- name: CRON | Create the "pull & restart" job
  cron:
    name: "coda green image check"
    cron_file: "/etc/crontab"
    user: "root"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "( flock -s 800; /usr/local/sbin/coda_green_podman_wrapper.sh > /var/log/ansible/coda_green_podman_wrapper-$( date +\\%Y\\%m\\%d-\\%H\\%M\\%S ).log 2>&1 ) 800>/var/lock/coda_green"
