---
# This series of operations simply stops the aidbox and aidboxdb containers
# and prune all containers images. As this role runs just before the _green and
# _orange roles, those latter will re-pull all needed images. Also, as we overrides
# some configuration values on a per-site bases (see group_vars ), any configuration
# file will be up-to-date.

- name: STAT | Cookie file /etc/coda19/migration_fihr_v3_v4
  stat:
    path: /etc/coda19/migration_fihr_v3_v4
  register: _stat

- block:

    ######
    ###### AIDBOX
    ######

    # Stop service, and force process removal

    - name: SYSTEMD | Stopping AidBox
      ignore_errors: yes
      systemd:
        name: aidbox
        state: stopped

    - name: SHELL | pkill for aidbox user
      shell: |
        pkill -U aidbox --signal SIGKILL
        pkill -u aidbox --signal SIGKILL

    - name: SHELL | podman prune (AidBox)
      shell: |
        podman system prune --all --force --volumes
        podman image  prune --all
      become: yes
      become_user: aidbox

    ######
    ###### AIDBOXDB
    ######

    # Stop service, and force process removal

    - name: SYSTEMD | Stopping AidBoxDB
      ignore_errors: yes
      systemd:
        name: aidboxdb
        state: stopped

    - name: SHELL | pkill for aidboxdb user
      shell: |
        pkill -U aidboxdb --signal SIGKILL
        pkill -u aidboxdb --signal SIGKILL

    - name: SHELL | podman prune (AidBOXDB)
      shell: |
        podman system prune --all --force --volumes
        podman image  prune --all
      become: yes
      become_user: aidboxdb

    # Purge all Postgresql datafiles. Ansible has no somple way to do this.. use a SHELL statement
    - name: SHELL | removing Postgresql data files
      shell: rm -rf /data/aidboxdb/*

    ######
    ###### MARK THIS MIGRATION AS DONE!
    ######

    - name: FILE | Touch cookie file /etc/coda19/migration_fihr_v3_v4
      file:
        path: /etc/coda19/migration_fihr_v3_v4
        state: touch

  when: not _stat.stat.exists or _oneoffs_migration_fhir4_ignore_cookiefile
