---

###### FIX ORTHANC

- when:
    - coda19_site_id|int == 110
    - coda19_host_role == 'orange'
  block:

    - name: SET_FACT | _cookie_value + _cookie_file
      set_fact:
        _cookie_value: "20220727-03"
        _cookie_file: /etc/coda19/oneoff-fix-orthanc-service

    - name: "SLURP | Check for cookie file - {{ _cookie_file }}"
      slurp:
        src: "{{ _cookie_file }}"
      ignore_errors: yes
      register: _slurp

    - when: _slurp.failed or _slurp['content'] | b64decode | string != _cookie_value | string
      block:

        - name: SYSTEMD | Stop orthanc service
          systemd:
            name: orthanc
            state: stopped

        - name: SHELL | Do our stuff
          shell: |
            pkill -U orthanc --signal SIGTERM
            pkill -u orthanc --signal SIGTERM
            sleep 10
            pkill -U orthanc --signal SIGKILL
            pkill -u orthanc --signal SIGKILL
            rm -rf /tmp/orthanc* /data/orthanc*
            sudo -i -u orthanc "/usr/bin/podman system prune --all --force"
            sudo -i -u orthanc "/usr/bin/podman rmi --all"
          failed_when: false
          register: _shell

        - debug:
            var: _shell

        - name: COPY | Mark as done
          copy:
            dest: "{{ _cookie_file }}"
            content: "{{ _cookie_value }}"
