---

ul_aidbox_firewalld_zones:
  - zone: public
    state: enabled

# Aidbox.One listening port (TCP)

ul_aidbox_port: 8888

ul_aidbox_db_owner: aidbox
ul_aidbox_db_name: aidbox
ul_aidbox_db_host: 127.0.0.1
ul_aidbox_db_port: 5432

# Those are used for aidbox_svc.conf.j2

ul_aidbox_conf_admin_id: admin
ul_aidbox_conf_admin_password: password

ul_aidbox_conf_client_id: client
ul_aidbox_conf_client_secret: secret

ul_aidbox_image_registry: docker.io
ul_aidbox_image: healthsamurai/aidboxone
ul_aidbox_image_tag: 0.5.0-SNAPSHOT

ul_aidbox_db_image_registry: docker.io
ul_aidbox_db_image: aidbox/db
ul_aidbox_db_image_tag: 13.0.0

# Startup timeouts expressed in seconds
ul_aidbox_wu_timeout: 120
ul_aidbox_db_wu_timeout: 120
