---
#TODO: Manage more than one zone
ul_aidbox_firewall_zone: public

# Aidbox.One listening port (TCP)
ul_aidbox_port: 8888

ul_aidbox_db_owner: aidbox
ul_aidbox_db_name: aidbox

# Those are used for aidbox_svc.conf.j2
# TODO: Generate "real" passwords in vaults
ul_aidbox_svc_conf_admin_login: admin
ul_aidbox_svc_conf_admin_password: secret
ul_aidbox_svc_conf_client_id: root
ul_aidbox_svc_conf_client_secret: secret

ul_aidbox_image: docker.io/healthsamurai/aidboxone
ul_aidbox_image_tag: 0.5.0-SNAPSHOT
