---

ul_aidbox_firewalld_zones:
  - zone: public
    state: enabled

# Aidbox.One listening port (TCP)

ul_aidbox_port: 8888

ul_aidbox_db_owner: aidbox
ul_aidbox_db_name: aidbox

# Those are used for aidbox_svc.conf.j2

ul_aidbox_conf_admin_id: admin
ul_aidbox_conf_admin_password: password

ul_aidbox_conf_client_id: client
ul_aidbox_conf_client_secret: secret

ul_aidbox_image: docker.io/healthsamurai/aidboxone
ul_aidbox_image_tag: 0.5.0-SNAPSHOT
