---

#------------------------------------------------------------------------------
# GENERAL SETTINGS
#------------------------------------------------------------------------------

# Use latest version from upstream project rather than from official repositories or EPEL
# This simply follow these instructions: https://podman.io/getting-started/installation

ul_podman_install_upstream: yes

# Maximum namespaces per user

ul_podman_max_user_namespaces: 65536
