---
#
# How to invoke on localhost:
#
#   env-ansible
#   ansible-playbook --inventory hosts.localhost playbooks/localhost.yml
#
- name: Deploy the current box based on local facts (coda19.host.role)
  hosts: all
  connection: local
  vars_files:
    - "{{ inventory_dir }}/vaults/vault.{{ ansible_local.coda19.site.id }}"
  tasks:
    - name: INCLUDE_ROLE | _ORANGE
      include_role:
        name: _orange
      when: "ansible_local.coda19.host.role|lower == 'orange'"

    - name: INCLUDE_ROLE | _GREEN
      include_role:
        name: _green
      when: "ansible_local.coda19.host.role|lower == 'green'"
