---
#
# For invocation instructions and examples, see remote.yml playbook.
#

- name: DEPLOY AND MAINTAIN THE «GREEN BOXES»
  hosts: green
  become: yes
  environment:
    http_proxy:  "{{ _common_global_proxy   | default('') }}"
    https_proxy: "{{ _common_global_proxy   | default('') }}"
    no_proxy:    "{{ _common_global_noproxy | default('') }}"
    HTTP_PROXY:  "{{ _common_global_proxy   | default('') }}"
    HTTPS_PROXY: "{{ _common_global_proxy   | default('') }}"
    NO_PROXY:    "{{ _common_global_noproxy | default('') }}"

  vars_files:

    # NOTE: This file list must be identical for all playbooks: localhost.yml, remote-orange.yml, remote-green.yml
    - "{{ playbook_dir }}/../group_vars/all"
    - "{{ playbook_dir }}/../group_vars/{{ ansible_local.coda19.site.id }}"
    - "{{ playbook_dir }}/../vaults/vault.{{ ansible_local.coda19.site.id }}"

  pre_tasks:

    - name: SET_FACT | Set coda19_host_role to "green"
      set_fact:
        coda19_host_role: green
      tags:
        - always

    # Try to load specific vars for this node role (orange|green).

    - name: INCLUDE_VARS | Node's role specific vars
      include_vars: "{{ item }}"
      failed_when: false
      loop:
        - "{{ playbook_dir }}/../group_vars/{{ coda19_site_id }}.{{ coda19_host_role | lower }}"
        - "{{ playbook_dir }}/../vaults/vault.{{ coda19_site_id }}.{{ coda19_host_role | lower }}"
      tags:
        - always

  tasks:

    - name: INCLUDE_ROLE | _ONEOFFS
      include_role:
        name: _oneoffs
      tags:
        - always

    - name: INCLUDE_ROLE | _GREEN
      include_role:
        name: _green
      when: coda19_host_role == "green"
      tags:
        - always

    - name: FILE | Remove file /etc/coda19/boostrapping
      file:
        path: /etc/coda19/bootstrapping
        state: absent
      tags:
        - always
