---
#
# For invocation instructions and examples, see remote.yml playbook.
#

- name: DEPLOY AND MAINTAIN THE «ORANGE BOXES»
  hosts: orange
  become: yes
  environment:
    http_proxy:  "{{ _common_global_proxy   | default('') }}"
    https_proxy: "{{ _common_global_proxy   | default('') }}"
    no_proxy:    "{{ _common_global_noproxy | default('') }}"
    HTTP_PROXY:  "{{ _common_global_proxy   | default('') }}"
    HTTPS_PROXY: "{{ _common_global_proxy   | default('') }}"
    NO_PROXY:    "{{ _common_global_noproxy | default('') }}"

  vars_files:

    # NOTE: This file list must be identical for all playbooks: localhost.yml, remote-orange.yml, remote-green.yml
    - "{{ playbook_dir }}/../group_vars/all"
    - "{{ playbook_dir }}/../group_vars/{{ ansible_local.coda19.site.id }}"
    - "{{ playbook_dir }}/../vaults/vault.{{ ansible_local.coda19.site.id }}"

  pre_tasks:

    - name: SET_FACT | Set coda19_host_role to "orange"
      set_fact:
        coda19_host_role: orange
      tags:
        - always

  tasks:

    - name: INCLUDE_ROLE | _ONEOFFS
      include_role:
        name: _oneoffs
      tags:
        - always

    - name: INCLUDE_ROLE | _ORANGE
      include_role:
        name: _orange
      when: coda19_host_role == "orange"
      tags:
        - always
