---
#
# REMOTE DEPLOYMENT
#
# For instructions, please refer to remote-green.yml playbook.
#
- name: Deploy and maintain the «orange boxes»
  hosts: orange
  become: yes
  environment:
    http_proxy: "{{ _common_global_proxy }}"
    https_proxy: "{{ _common_global_proxy }}"
    no_proxy: "{{ _common_global_noproxy }}"
    HTTP_PROXY: "{{ _common_global_proxy }}"
    HTTPS_PROXY: "{{ _common_global_proxy }}"
    NO_PROXY: "{{ _common_global_noproxy }}"
  vars_files:
    - "{{ inventory_dir }}/vaults/vault.{{ coda19_site_id }}"
  roles:
    - _orange
