---
- name: DEPLOY AND MAINTAIN THE «ORANGE BOXES»
  hosts: orange
  become: yes
  environment:
    http_proxy: "{{ _common_global_proxy }}"
    https_proxy: "{{ _common_global_proxy }}"
    no_proxy: "{{ _common_global_noproxy }}"
    HTTP_PROXY: "{{ _common_global_proxy }}"
    HTTPS_PROXY: "{{ _common_global_proxy }}"
    NO_PROXY: "{{ _common_global_noproxy }}"
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all"
    - "{{ inventory_dir }}/group_vars/{{ coda19_site_id }}"
    - "{{ inventory_dir }}/vaults/vault.{{ coda19_site_id }}"
  roles:
    - _oneoffs
    - _orange
