---
#
# REMOTE DEPLOYMENT
#
# For instructions, please refer to remote-green.yml playbook.
#
- name: Deploy and maintain the «orange boxes»
  hosts: orange
  become: yes
  vars_files:
    - "{{ inventory_dir }}/vaults/vault.{{ coda19_site_id }}"
  roles:
    - _orange
