---
#
# REMOTE DEPLOYMENT
#
# ansible-playbook --inventory hosts.pr \
#                  --vault-password-file vault.115.pass \
#                  --user ul-a-brlav35 \
#                  --ask-become-pass \
#                  playbooks/remote.yml \
#                  --limit s115
#

- name: Include «orange» playbook
  import_playbook: remote-orange.yml

- name: Include «green» playbook
  import_playbook: remote-green.yml
