---

- name: Bootstrap site config on this host
  hosts: localhost

  vars_prompt:

    - prompt: "Enter your site ID (110-120): "
      name: _input_site_id
      private: no

    - prompt: "Enter this host's role [orange|green]: "
      name: _input_host_role
      private: no

    - prompt: "Enter provided passphrase: "
      name: _input_site_passphrase
      private: no

  tasks:

    - name: FILE | Ensure /etc/ansible/facts.d directory is present
      file:
        path: /etc/ansible/facts.d/
        state: directory

    - name: FILE | Ensure /etc/ansible/facts.d/coda19.fact files is present
      file:
        path: /etc/ansible/facts.d/coda19.fact
        owner: root
        group: root
        mode: 0644

    - name: INI_FILE | Add entries to /etc/ansible/facts.d/coda19.facts
      ini_file:
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - section: site
          option: id
          value: "{{ _input_site_id }}"
        - section: host
          option: role
          value: "{{ _input_host_role }}"

    - name: COPY | Create vault.pass file
      copy:
        content: "{{ _input_site_passphrase }}"
        dest: /opt/coda19/deploy-scripts/ansible/vault.pass
