---

- name: PLAY to develop roles using Vagrant
  hosts: all
  vars:
    env: local
  #vars_files:
  #  - "{{ inventory_dir }}/group_vars/vault.{{ env }}"
  roles:
    # Put here the roles you want to test
    - _common
