---

### Group and user

- name: "GROUP | Add the group {{ ul_orthanc_group }}"
  group:
    name: "{{ ul_orthanc_group }}"
    system: no

- name: "USER | Add the user {{ ul_orthanc_user }}"
  user:
    name: "{{ ul_orthanc_user }}"
    comment: "orthanc account"
    group: orthanc
    home: /var/lib/orthanc
    system: no

### Configurations

- name: "FILE | Create /data/orthanc/"
  file:
    dest: /data/orthanc
    owner: orthanc
    group: orthanc
    mode: 0750
    state: directory

- name: "FILE | Create /etc/orthanc/"
  file:
    path: /etc/orthanc
    state: directory
    owner: orthanc
    group: orthanc
    mode: 0640

- name: "TEMPLATE | Generate /etc/default/orthanc"
  template:
    src: etc/default/orthanc.j2
    dest: /etc/default/orthanc
    owner: orthanc
    group: orthanc
    mode: 0640
  notify: restart orthanc

- name: "TEMPLATE | Generate /etc/orthanc/orthanc.json"
  template:
    src: etc/orthanc/orthanc.json.j2
    dest: /etc/orthanc/orthanc.json
    owner: orthanc
    group: orthanc
    mode: 0640
  notify: restart orthanc

### Service files

- name: "TEMPLATE | Copy systemd service unit"
  template:
    src: etc/systemd/system/orthanc.service.j2
    dest: /etc/systemd/system/orthanc.service
    owner: root
    group: root
    mode: 0664
  register: _systemd_service
  notify: restart orthanc

- name: "SYSTEMD | Reload daemon"
  systemd:
    daemon_reload: yes
  when: _systemd_service.changed

### Invoke the puller

- name: "INCLUDE_TASKS | roles/ul_podman/tasks/puller.yml"
  include_tasks: "{{ playbook_dir }}/../roles/ul_podman/tasks/puller.yml"
  vars:
    _image_repo: "{{ ul_orthanc_image_repo }}"
    _image_name: "{{ ul_orthanc_image_name }}"
    _image_tag: "{{ ul_orthanc_image_tag }}"
    _image_user: "{{ ul_orthanc_user }}"
    _image_change_handler: restart orthanc
    _image_prune_enabled: true
    _remote_check_hours: "{{ ul_orthanc_image_remote_check_hours }}"
    _remote_check_runs: "{{ ul_orthanc_image_remote_check_runs }}"

### Ensure orthanc service is started and enabled

- name: SYSTEMD | Start and enable orthanc
  systemd:
    name: orthanc
    state: started
    enabled: yes
