---

- block:

    - name: YUM | Install epel-release and elrepo-release
      yum:
        name:
          - epel-release
          - elrepo-release
        state: present

    - name: YUM | Install yum-plugin-elrepo
      yum:
        name: yum-plugin-elrepo
        state: present

    - name: YUM | Install wireguard packages
      yum:
        name:
          - kmod-wireguard
          - wireguard-tools
        state: present

    - name: MODPROBE | Ensure required kernel-modules are loaded
      modprobe:
        name: wireguard
        state: present

    - name: COPY | Create /etc/modules-load.d/99-wireguard.conf
      copy:
        dest: /etc/modules-load.d/99-wireguard.conf
        content:
          wireguard

  tags:
    - ul_wireguard
