---
- name: "IMPORT_TASKS | firewall.yml"
  import_tasks: firewall.yml
  tags:
    - ul_coda19_green
    - ul_coda19_green_firewall

- name: "IMPORT_TASKS | install.yml"
  import_tasks: install.yml
  tags:
    - ul_coda19_green
    - ul_coda19_green_install
