---

- block:

      - name: YUM | Install required packages
        yum:
          name: epel-release
          state: present

      - name: YUM | Install snapd
        yum:
          name: snapd
          state: present

      # sudo systemctl enable --now snapd.socket

      - name: SYSTEMD | Enable snapd.socket
        systemd:
          name: snapd.socket
          state: started
          enabled: yes

      - name: FILE | Create symlink for enabling classic snaps
        file:
          src: /var/lib/snapd/snap
          dest: /snap
          state: link

      - name: "SNAP | Install microk8s using {{ ul_microk8s_channel }}"
        snap:
          name: microk8s
          channel: "{{ ul_microk8s_channel }}"
          state: present
          classic: yes

      - name: "COMMAND | Waiting for microk8s to become ready..."
        command: "/var/lib/snapd/snap/bin/microk8s status --wait-ready --timeout {{ ul_microk8s_ready_timeout }}"
        changed_when: false
        register: _microk8s_status

      - name: COMMAND | Manage addons
        command: "/var/lib/snapd/snap/bin/microk8s {{ item.action | default('enable' )}} {{ item.name }}"
        with_items: "{{ ul_microk8s_addons }}"
        register: _addons
        changed_when: not 'already enabled' in _addons.stdout   

  tags: ul_microk8s
